# TODO: document how the grafana docker image used in this file is built
# on panakeia stable:
# 0. build a docker image named grafana using the following steps....
# 1. nix develop
# 2. poetry install
# 3. ./panakeia create-composition --env test
# 4. poetry env activate | source
# 5. ./panakeia create-composition --env test
# 6. docker buildx bake --file docker/nickel_output/bake-test.hcl grafana

services:
  grafana-a:
    image: grafana
    container_name: grafana-a
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-a-storage:/var/lib/grafana

  grafana-b:
    image: grafana
    container_name: grafana-b
    restart: unless-stopped
    ports:
      - '3001:3000'
    volumes:
      - grafana-b-storage:/var/lib/grafana

volumes:
  grafana-a-storage: {}
  grafana-b-storage: {}
