name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Setup Java JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'

      # https://github.com/babashka/babashka#ci
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@13.4
        with:
          bb: 1.12.218 # Babashka

      - name: Get babashka version
        run: bb --version

      - name: Run tests
        run: bb test
